### PR TITLE
Bug/equippable being consumed

### PR DESCRIPTION
**Pull request by FathomlessFunction**
Fixed bug - equippables being consumed on equip.
Created test to replicate bug.
Also added equippable to player's inventory in mainmenu for playtesting.

### CODE REVIEW

**Review by TehPlazmon — CHANGES_REQUESTED** [review]
Tested this, equipped sword with the (equip) command, attack was correctly increased by 5, and sword stayed in inventory. 
Tried to unequip sword with the (equip) command, but the sword seemed to equip itself twice, further increasing the attack by 5, rather than decreasing it.

**Comment by FathomlessFunction** [comment]
I believe the last two commits have fixed the bug you found.

**Review by TehPlazmon — APPROVED** [review]
Works as expected!

**Comment by TehPlazmon** [comment]
Works correctly after some aggressive play-testing.

**Pull request merged**
